✨ Requires interface improvements
fernandomema/Zumito pull request #51
Opened 2022-09-19 18:54 UTC by WilliamAcosta1

- Added Spanish translation
- Added color to the embed.
-  Added emojis.ts
- Requires some fixes.

Conclusion: Discussion in private channel is required for improvements

2022-09-20 13:29 UTC, fernandomema requested changes

2022-09-20 15:47 UTC, WilliamAcosta1 reviewed
Hacer funcional aliases.
Agregar menu a embed cuando se ejecute con prefix.
Mantener la seleccion de una categoria.
Agregar a slashcommands

2022-09-21 18:47 UTC, WilliamAcosta1 commented
- Hacer las categorías traducibles
- Agregar la traducción de las categorías y emoji

2022-09-21 23:37 UTC, WilliamAcosta1 commented
Todo acorde

2022-09-22 16:57 UTC, fernandomema approved these changes

2022-09-22 16:59 UTC, merged